import Link from 'next/link'
import Head from 'next/head'
import Router from 'next/router'
import axios from 'axios'
import { useState, useEffect } from 'react'


import Header from '../../components/Header.jsx'
import * as Icon from 'react-cryptocoins';


export default function CrearPgo(){

    const [userLogged, setUserLogged] = useState(null)
    const [amount, setAmount] = useState(0)
    const [currency, setCurrency] = useState(null)
    const [description, setDescription] = useState('')


    useEffect(()=>{
        if(localStorage.getItem('user')){
        setUserLogged(JSON.parse(localStorage.getItem('user')))
        }
    }, [])

    

    const fetchData = async () => {
        const dataCharge = {
            amount: amount.toString(),
            currency,
            description,
            customer_name: userLogged.name,
            customer_id: userLogged._id
        }
        axios.get('/api/charges', {params: dataCharge})
            .then(res =>{
                console.log(res)
                localStorage.lastPaymentMade = JSON.stringify(res.data)
                Router.push('/pago-creado')
            })
            .catch(err =>{
                console.log(err)
            })

    };

    const handleClick = (event) => {
        event.preventDefault();
        fetchData();
    };

    const handleChangeAmount = (event)=>{
        setAmount(event.target.value)
    }

    const handleChangeCurrency = (event)=>{
        setCurrency(event.target.value)

    }

    const handleChangeDescription = (event)=>{
        setDescription(event.target.value)
    }
    
    return (
        <div>
            <Head>
            <title>Bitpayer - Bitcoin hecho fácil.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            <link href="https://fonts.googleapis.com/css2?family=Sarabun:ital,wght@0,200;0,300;0,400;0,600;0,800;1,300;1,400;1,600;1,800&family=Vollkorn&display=swap" rel="stylesheet" />
            </Head>

            <Header />
            <main>

            <section class="position-top-section border-top-3-blue">
                        <div>
                            <section class="back-darkblue-gradient width100 padding20-10">

                                <article class="my-container">

                                    <div class="flex flex-middle flex-between">
                                        <div class="widthHalf-desktop">
                                            <h2 class="font2-5em color-white margin-bottom20">Aceptar <span class="color-green">Pagos en Bitcoin</span> incrementará tus ingresos.</h2>

                                            <p class="font1-5em color-white margin-bottom20">Crea un pago con el monto a recibir por tu cliente, muéstrale el código QR al instante o envía la liga de pago.</p>

                                            <div className='padding20-0'>
                                                <button class="my-btn back-green color-green call-wrap-actions-button">
                                                    <span class="font1em color-white">Agendar ahora</span>
                                                </button>

                                                <p class="color-yellow anchor font20">¿Cómo hacerlo?</p>
                                            </div>
                                            
                                        </div>

                                        <div class="widthHalf-desktop relative flex flex-right">
                                            <div>
                                                <div className='payment-form'>
                                                    <div className='margin10'>
                                                      <h2 className='font1-3em  text-center'>Crear Pago</h2>  
                                                    </div>

                                                    <article>
                                                        <div className='flex flex-middle'>
                                                            <div className='margin10'>
                                                                <h2 className='font1em margin-bottom5'>Cantidad:</h2>
                                                                <div className='flex'>
                                                                    <div className='flex'>
                                                                        <input className='my-input' type="number" onChange={handleChangeAmount}/>
                                                                    </div>

                                                                    <div className="back-white my-select font1em color-black" style={{width:100+"px"}}>
                                                                        <select onChange={handleChangeCurrency}>
                                                                            <option>-</option>
                                                                            <option value="MXN">MXN</option>
                                                                            <option value="USD">USD</option>
                                                                        </select>
                                                                        
                                                                        <div class="my-select-icon color-black flex flex-middle">
                                                                            <span class="ion-arrow-down-b"></span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                
                                                            </div>

                                                            <div className='margin10'>
                                                                <h2 className='font1em opacity0 margin-bottom5'>|</h2>
                                                                
                                                            </div>
                                                        </div>

                                                        <div className='margin10'>
                                                            <h2 className='font1em margin-bottom5'>Descripción:</h2>
                                                            <div className='flex'>
                                                                <textarea className='my-input' rows={3} onChange={handleChangeDescription}/>
                                                            </div>
                                                        </div>
                                                        {/* <div className='margin10'>
                                                            <button  className='my-btn back-green'>Crear pago</button>
                                                        </div> */}

                                                        <div class="padding10 margin15-0" style={{position: 'static;'}}>
                                                            <button onClick={handleClick} class="my-btn back-darkblue-gradient block color-green" style={{width: 100+"%"}}>
                                                                <span class="font1-3em color-white">Continuar</span>
                                                            </button>
                                                        </div>
                                                        <div>
                                                            <p className='text-center color-gray'><em>Tu cliente podrá pagar con:</em></p>
                                                            <div className='flex flex-center'>
                                                                <span className='margin5'>
                                                                    <Icon.Btc color="orange" size={27}/>
                                                                </span>
                                                                <span className='margin5'>
                                                                    <Icon.Eth color="#737ade" size={27}/>
                                                                </span>
                                                                <span className='margin5'>
                                                                    <Icon.Ltc color="#3983d3" size={27}/>
                                                                </span>
                                                                <span className='margin5'>
                                                                    <Icon.Doge color="orange" size={27}/>
                                                               </span>
                                                                
                                                            </div>
                                                        </div>
                                                    </article>
                                                    
                                                </div> 
                                            </div>
                                            

                                            {/* <figure class="relative" style={{width:420+"px;", bottom:-60+"px;", right:30+"px;"}}>
                                                <img src="./estudio.png" class="width100" />
                                            </figure> */}
                                        </div>
                                    </div>

                                    
                                </article>

                                
                            </section>

                            
                            <div class="padding20"></div>
                            <div class="padding20"></div>
                    </div>
                </section>

                <section className='my-container'>
                    <div className='padding20'></div>
                </section>

            </main>
            
        </div>
    )
}