import Link from 'next/link'
import Head from 'next/head'
import axios from 'axios'
import { useState, useEffect } from 'react'
import QRCode from 'react-qr-code'

import Header from '../../components/Header.jsx'


import * as Icon from 'react-cryptocoins';



export default function PagoCreado() {
	// const [userLogged, setUserLogged] = useState(null)
	// const [amount, setAmount] = useState(0)
	// const [currency, setCurrency] = useState(null)
	const [payment, setPayment] = useState(null)
	const [paymentSelected, setPaymentSelected] = useState(null)

	useEffect(() => {
		if (localStorage.getItem('lastPaymentMade')) {
			setPayment(JSON.parse(localStorage.getItem('lastPaymentMade')))
		}
	}, [])

	// const fetchData = async () => {
	//     const dataCharge = {
	//         amount: amount.toString(),
	//         currency,
	//         description,
	//         customer_name: userLogged.name,
	//         customer_id: userLogged._id
	//     }
	//     axios.get('/api/charges', {params: dataCharge})
	//         .then(res =>{
	//             console.log(res)
	//         })
	//         .catch(err =>{
	//             console.log(err)
	//         })

	// };

	const handlePaymentSelected = (
		paymentSelectedName,
		paymentSelectedAddress
	) => {
		setPaymentSelected({
			name: paymentSelectedName,
			address: paymentSelectedAddress,
		})
	}

	return (
		<div>
			<Head>
			<title>Bitpayer - Bitcoin hecho fácil.</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			<link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
			<link rel="preconnect" href="https://fonts.googleapis.com" />
			<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
			<link href="https://fonts.googleapis.com/css2?family=Sarabun:ital,wght@0,200;0,300;0,400;0,600;0,800;1,300;1,400;1,600;1,800&family=Vollkorn&display=swap" rel="stylesheet" />
			</Head>

			<Header />
			<main>
				<div className='padding20'></div>
				<div className='padding20'></div>

				<div className='padding20'>
					<h2 className='font2em text-center'>
						Listado de pagos creados
					</h2>
				</div>


				<section className='my-container'>
                    <div>
                        <div>
                            <p>PaymentId: </p>
                            <p>PaymentId: </p>
                            <p>Descripccion: </p>
                        </div>
                        

                        <div>
                            <p>Estatus: </p>
                            <p>Fecha de creación: </p>
                        </div>
                        
                    </div>
				</section>
			</main>
		</div>
	)
}
