import Link from 'next/link'
import Head from 'next/head'
import axios from 'axios'
import { useState, useEffect } from 'react'


import Header from '../../components/Header.jsx'

export default function PagoCreado(){

    // const [userLogged, setUserLogged] = useState(null)
    // const [amount, setAmount] = useState(0)
    // const [currency, setCurrency] = useState(null)
    const [payment, setPayment] = useState(null)

    

    useEffect(()=>{
        if(localStorage.getItem('lastPaymentMade')){
        setPayment(JSON.parse(localStorage.getItem('lastPaymentMade')))
        }
    }, [])

    

    // const fetchData = async () => {
    //     const dataCharge = {
    //         amount: amount.toString(),
    //         currency,
    //         description,
    //         customer_name: userLogged.name,
    //         customer_id: userLogged._id
    //     }
    //     axios.get('/api/charges', {params: dataCharge})
    //         .then(res =>{
    //             console.log(res)
    //         })
    //         .catch(err =>{
    //             console.log(err)
    //         })

    // };

    // const handleClick = (event) => {
    //     event.preventDefault();
    //     fetchData();
    // };

    // const handleChangeAmount = (event)=>{
    //     setAmount(event.target.value)
    // }

    // const handleChangeCurrency = (event)=>{
    //     setCurrency(event.target.value)

    // }

    // const handleChangeDescription = (event)=>{
    //     setDescription(event.target.value)
    // }
    
    return (
        <div>
            <Head>
            <title>Bitpayer - Bitcoin hecho fácil.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
            <link href="https://fonts.googleapis.com/css?family=Poppins|Lakki+Reddy|Rancho&display=swap" rel="stylesheet" />
            
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            </Head>

            <Header />
            <main>

                <div className='padding20'></div>
                <div className='padding20'></div>

                <div className='padding20'>
                    <h2 className='font2em text-center'>¡Tu pago por {payment && <span className='color-green'>${payment.pricing.local.amount}{payment.pricing.local.currency}</span>} ha sido creado!</h2>
                </div>

                <div className='padding20'>
                    <p className='font1-3em text-center padding5'>Dale click en el botón  "ver pago" para mostrarle <br/>  el código QR a tu cliente y pague al instante.</p>

                    <p className='font1-3em text-center padding5'>También puedes darle click al botón copiar para mandarle a tu cliente <br/> la liga de pago por la compra de tu producto/servicio.</p>
                </div>

                <section className='my-container'>
                    <article className='padding20'>
                        
                    </article>
                </section>

            </main>
            
        </div>
    )
}