import Link from 'next/link'
import Head from 'next/head'

import Header from '../../components/Header.jsx'

export default function About(){
    return (
        <div>
            <Head>
            <title>Bitpayer - Bitcoin hecho fácil.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
            <link href="https://fonts.googleapis.com/css?family=Poppins|Lakki+Reddy|Rancho&display=swap" rel="stylesheet" />
            
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
            </Head>

            <Header />
            <main>
                <h2 className="color-red">About</h2>
                <Link href="/">Got to home</Link>
            </main>
            
        </div>
    )
}