import Head from 'next/head'
import Link from 'next/link'

import Header from '../components/Header.jsx'
import Footer from '../components/Footer.jsx'
import Content from '../components/Content.jsx'


import Image from 'next/image'

const imgHand = "./payment-phone-dark.png"

export default function Home() {
  return (
    <div id="app-container">
      <div>
        <Head>
          <title>Bitpayer - Bitcoin hecho fácil.</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Sarabun:ital,wght@0,200;0,300;0,400;0,600;0,800;1,300;1,400;1,600;1,800&family=Vollkorn&display=swap" rel="stylesheet" />
        </Head>

        <Header />

        <main>
        <section>
		      <div class=" relative" style={{minHeight:95+"vh;", zIndex: 10}}>
		        
		        <article class=" padding10-0 my-container call-wrap">
		        <br />
		        <br />
		          {/* <!-- <img src="./common-bg1.png" class="width100  call-wrap-img-pattern" > -->
		          <!-- <img src="./wave.png" class="width100 call-wrap-img-wave" style=""> --> */}
		          <div class="relative padding15" style={{zIndex: 10, paddingTop:50+"px;"}}>
		            <article class=" flex flex-between flex-middle">
		              <div class="relative" style={{top:-20+"px;"}}>
		                {/* <!-- <h1 class="font2em color-white call-wrap-main-text">Todo es más fácil con el celular <br /> pagar con <span class="color-green text-shadow-white1">Bitcoin</span>  también.</h1> --> */}

		                <h1 class="font2-7em  call-wrap-main-text">Toma control sobre tu dinero. <br /> Con <span class="color-green text-shadow-white1">Bitcoin</span>,  eres tu propio banco.</h1>

		                <h2 class="font1-7em font-normal call-wrap-second-text">
		                  Expande tus opciones de pago  de forma<br /> instantanea, sin riesgo ó fluctuación de precio.
		                </h2>

		                


		                <div class="call-wrap-actions margin-bottom30">
						{
							!userLogged && <Link href="/login">
							<a className="my-btn back-green text-uppercase color-green contactanos">
								<span className="font1em color-white">Iniciar Sesión</span>
							</a>
							</Link>
						}
		                  <a href="#ex1" class="anchor color-blue font1-5em" rel="modal:open">¿Qué es Bitcoin? </a>
		                  {/* <!-- <a class="anchor font1-3em color-white call-wrap-actions-video" href="#" style="padding-bottom: 3px">
		                    <span class="show-desktop margin-right5">Ver como</span>
		                    
		                    <span class="ion-play"></span>
		                  </a> --> */}
		                </div>


		                <div>
		                  <p class="margin-bottom10 flex flex-middle">
		                    <span class="margin-right10 ion-android-checkmark-circle color-green font2em"></span>
		                    <span class="font1-5em">Elimina Riesgos</span>
		                  </p>

		                  <p class="margin-bottom10 flex flex-middle">
		                    <span class="margin-right10 ion-android-checkmark-circle color-green font2em"></span>
		                    <span class="font1-5em">Bitcoin Hecho Fácil</span>
		                  </p>



		                  <p class="flex flex-middle margin-bottom10">
		                    <span class="margin-right10 ion-android-checkmark-circle color-green font2em"></span>
		                    <span class="font1-5em">Dinero Sin Restricciones</span>
		                  </p>
		                  <p class="flex flex-middle">
		                    <span class="margin-right10 ion-android-checkmark-circle color-green font2em"></span>
		                    <span class="font1-5em">Aprende Bitcoin de forma efectiva</span>
		                  </p>

		                </div>
		              </div>

		              <div class="block-desktop hide relative">
		                {/* <!-- <figure style="width:500px;">
		                  <img src="https://www.acheck21.com/wp-content/uploads/2015/02/fintech-right.png" class="width100">
		                </figure> --> */}

		                <div class="cellphone-window">
		                  <div></div>
		                </div>



		                <figure class="relative" style={{width:390+"px;", zIndex:10, top:-35+"px;"}}>
		                  {/* <img  class="width100" /> */}
                      <Image src="/payment-phone-dark.png" width={135} height={142}/>
		                </figure>
		              </div>
		            </article>
		            
		            
		            

		            
		          </div>
		          {/* <!-- <div class="padding15 flex relative box-buy-btc center-block" style="top: 15px; padding-top: 0; z-index:100;">
		            <div class="call-wrap-buy-bitcoin-box padding20-0">
		              <div >
		                <h2 class="color-white text-uppercase font1em text-center">¿Necesitas Bitcoin?</h2>
		                <div class="back-green margin-top10 margin-bottom10 center-block" style="width:50px; height: 3px;"></div>

		                <div class=" flex flex-middle flex-center font1em width100" style="font-size: .91em">
		                  <p class="color-white text-right" style="width: 49%;">1 BTC = $<span id="bitcoinPrice">{{bitcoinPrice}}</span></p>
		                  <span class="color-green margin5 back-green" style="width: 3px; height: 20px;"></span>
		                  <p class="color-white text-left" style="width: 49%;"> $<span id="amountToBuy">{{amountToBuy}}</span> = <span id="bitcoinPrice100mxn">{{bitcoinPrice100mxn}}</span></p>
		                </div>
		                <div>
		                  <figure class="margin-top10 margin-bottom10 center-block" style="width: 50px">
		                    <img class="width100" src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Bitcoin.svg/600px-Bitcoin.svg.png">
		                  </figure>
		                  
		                </div>

		                <div class="flex flex-center color-white margin-bottom15">
		                  <button class="my-btn back-green">
		                    <span class="color-white">Comprar Bitcoin</span>
		                  </button>
		                </div>
		                <div class="flex flex-center color-white font1em" >
		                  <span class="fab fa-cc-visa font2em"></span>
		                  <span class="fab fa-cc-mastercard font2em margin0-10"></span>
		                  <span class="fab fa-cc-paypal font2em"></span>
		                </div>
		                <div class="padding-top10">
		                  <h4 class="text-center color-white">Powered By Hannahpay</h4>
		                </div>

		              </div>
		              
		            </div>
		            

		          </div>
		          <div class="padding20"></div> --> */}
		        </article>
		      </div>
		      
		    </section>

        <section class="back-white padding10">
		      
		      <br />
		      <br />

		      <div class="my-container flex-desktop flex-middle">
		        


		        <div class="widthHalf-desktop padding10">
		          <div class="block-section relative">
		            <h2 class="color-black font2em text-uppercase">¿Qué hacemos en BITPAYER?</h2>
		          </div>
		          <div class="padding5"></div>

		          <div class="relative margin-bottom20">
		            <p><span class="font1-4em">Si necesitas aprender sobre Bitcoin, aceptarlo como medio de pago personal o empresarial estás en el lugar correcto. En <span class="font-bold color-green">Bitpayer</span> ofrecemos varios métodos para configurar pagos en Bitcoin para cualquier sitio web o tienda física.  </span> </p>
		          </div>

		          <div class="relative margin-bottom20">
		            <p><span class="font1-4em"> Las opciones incluyen botones de pago, aplicaciones PoS web, integraciones API  y  plugins oficiales para las plataformas más importantes de e-commerce. <br /> También ofrecemos asesoría personal o empresarial sobre cualquier duda sobre el ecosistema Bitcoin. <br /><span class="anchor color-blue">Agenda una cita</span> y recibe una asesoría profesional.</span></p>
		          </div>

		        </div>

		        <div class="widthHalf-desktop">
		          <div class="stats flex  flex-center">
		            <div class="stats-item">
		                <figure class="stats-item-icon">
		                  <img src="./formacion.png" class="width100" />
		                </figure>

		                <p class="stats-item-number">130 +</p>

		                <p class="stats-item-title">Empresas activas</p>
		            </div>

		            <div class="stats-item">
		                <figure class="stats-item-icon">
		                  <img src="./solicitud.png" class="width100" />
		                </figure>

		                <p class="stats-item-number">1150 +</p>

		                <p class="stats-item-title">Pagos Realizados</p>
		            </div>
		          </div>

		          <div class="stats flex  flex-center">
		            <div class="stats-item">
		                <figure class="stats-item-icon">
		                  <img src="./vendedor.png" class="width100" />
		                </figure>

		                <p class="stats-item-number">150 +</p>

		                <p class="stats-item-title">Asesorías</p>
		            </div>

		            <div class="stats-item">
		                <figure class="stats-item-icon">
		                  <img src="./miembros.png" class="width100" />
		                </figure>

		                <p class="stats-item-number">20 +</p>

		                <p class="stats-item-title">Miembros del Equipo</p>
		            </div>
		          </div>
		        </div>
		        
		      </div>
		      <br />
		      <br />
		      <br />
		    </section>


		    <section class="padding10" style={{ background: "#F3F8FB;" }}>
		      <span class="relative" style={{top:-55+"px;"}} id="scrolledServices" ></span>
		      <br />

		      <div class="my-container" >
		        
		        <div class=" flex flex-center" >
		          <h2 class="color-black font2em text-uppercase margin-bottom10">Nuestros Servicios</h2>
		        </div>
		        <div class="flex flex-middle flex-center">
		          <div class="back-green" style={{width:40+"px;", height:5+"px;"}}></div>
		        </div>

		        <br />


		        <div class="margin-bottom20 flex flex-center">
		          <p class="text-center" style={{maxWidth:690+"px;"}}><span class="font1-5em text-center">Bitpayer es el mayor proveedor de servicios de pago con Bitcoin en México y parte de latinoamérica. También hemos creado la mejor metodología para el aprendizaje rápido y eficáz de esta tecnología.</span></p>
		        </div>


		        <div class="padding20">
		        	<div class="width100 flex flex-center">
		          

			          <section>
			            <article class="flex-desktop flex-center
			            ">

			              <div class="services-item">
			                <div class="square35 rounded back-darkblue-gradient flex flex-center flex-middle services-item-number">
			                  <span class="font20 relative color-white" style={{top:-1+"px;"}}>1</span>
			                </div>
			                <figure class="services-item-icon">
			                  <img src="./mostrador.png" class="width100" />
			                </figure>

			                <div class="margin15-0">
			                  <p class="font2em color-darkblue">Pagos</p>
			                </div>

			                <p class="font1-3em margin-bottom20">Configure su infraestructura de pagos, realice un seguimiento de los pedidos y administre sus ganancias en Bitcoin con estilo. Una plataforma global, versátil y totalmente integrada a la cartera digital de su celular.</p>

			                <div class="flex flex-center services-item-btn">
			                  <button class="my-btn back-darkblue-gradient block color-green">
			                    <span class="font1-3em color-white relative" style={{left:"2px;"}}>Más información <span class="ion-arrow-right-c font1em relative" style={{top:3+"px;"}}></span></span>
			                  </button>
			                </div>
			                
			              </div>
			              <div class="services-item">
			                <div class="square35 rounded back-darkblue-gradient flex flex-center flex-middle services-item-number">
			                  <span class="font20 color-white relative" style={{top:-1+"px;"}}>2</span>
			                </div>
			                <figure class="services-item-icon">
			                  <img src="./colegio.png" class="width100" />
			                  {/* <!-- <img src="./graduado.png" class="width100"> --> */}
			                </figure>

			                <div class="margin15-0">
			                  <p class="font2em color-darkblue">Educación</p>
			                </div>

			                <p class="font1-3em margin-bottom20">
                        {/* <!-- En nuestra <span class="font-bold color-green">Escuela Bitcoin</span> --> */}
                        Desde los conceptos básicos de Bitcoin, su uso y  hasta por qué está cambiando el mundo. Obtén respuestas simples a sus principales dudas sobre Bitcoin. ¿Listo para explorar? Vayamos a las estrellas.</p>

			                <div class="flex flex-center services-item-btn">
			                  <button class="my-btn back-darkblue-gradient block color-green">
			                    <span class="font1-3em color-white relative" style={{left:2+"px;"}}>Más información <span class="ion-arrow-right-c font1em relative" style={{top:3+"px;"}}></span></span>
			                  </button>
			                </div>
			                
			              </div>
			            </article>

			            <article class="flex-desktop flex-center">

			              <div class="services-item">
			                <div class="square35 rounded back-darkblue-gradient flex flex-center flex-middle services-item-number">
			                  <span class="font20 relative color-white" style={{top:-1+"px;"}}>3</span>
			                </div>
			                <figure class="services-item-icon">
			                  <img src="./supermercado.png" class="width100" />
			                </figure>

			                <div class="margin15-0">
			                  <p class="font2em color-darkblue">Productos</p>
			                </div>

			                <p class="font1-3em margin-bottom20">Encuentra en nuestra selécta variedad de productos aquellos que estamos seguros que te aportan valor. Todos los productos los entregamos totalmente nuevos y con las garantías esperadas. </p>

			                <div class="flex flex-center services-item-btn">
			                   <button class="my-btn back-darkblue-gradient block color-green">
			                    <span class="font1-3em color-white relative" style={{left:2+"px;"}}>- Próximamente -</span>
			                  </button>
			                </div>
			                
			              </div>
			              <div class="services-item">
			                <div class="square35 rounded back-darkblue-gradient flex flex-center flex-middle services-item-number">
			                  <span class="font20 color-white relative" style={{top:-1+"px;"}}>4</span>
			                </div>
			                <figure class="services-item-icon">
			                  <img src="./comercio.png" class="width100" />
			                </figure>

			                <div class="margin15-0">
			                  <p class="font2em color-darkblue">Trading</p>
			                </div>

			               {/* <!--  <figure class="services-item-icon">
			                  <img src="./comercio.png" class="width100">
			                </figure>

			                <div class="margin15-0">
			                  <p class="font2em color-darkblue">Compra/Venta</p>
			                </div> --> */}

			                <p class="font1-3em margin-bottom20">Te enseñamos a cómo lograr los mismos resultados de un comerciante de Bitcoin profesional sin asumir los riesgos inherentes. Bitcoin es dinero sólido y es la única alternativa digital que promete cumplir este objetivo.</p>

			                <div class="flex flex-center services-item-btn">
			                   <button class="my-btn back-darkblue-gradient block color-green">
			                    <span class="font1-3em color-white relative" style={{left:2+"px;"}}>Más información <span class="ion-arrow-right-c font1em relative" style={{top:3+"px;"}}></span></span>
			                  </button>
			                </div>
			                
			              </div>
			            </article>
			            
			            
			          </section>
			          
			        </div>

			        <br/>
			        <br/>
			      </div>
		        	
		        </div>
		        

		    </section>


		    <section class="back-darkblue padding20 color-white">
		    	<div class="padding20">
		    		<div class="flex flex-center">
			    		<figure style={{width:180+"px;"}}>
			    			<img src="./booksingle.png" class="width100" />
			    		</figure>
			    	</div>

			    	<div>
			    		<h3 class="font1-5em text-center">Sabemos que siempre tendrás dudas.</h3>
			    		<h3 class="font1-5em text-center">Accede al glosario de términos básicos sobre Bitcoin y Blockchain.</h3>
			    	</div>

			    	<div class="flex flex-center margin-top20">
			    		<a href="/diccionario.html" class="my-btn back-green color-green">
			              <span class="font1-3em color-white">Ver Diccionario</span>

			            </a>
			    	</div>
		    	</div>
		    	
		    </section>

        <section class="back-white padding10">
		      
		      <br />
		      <br />

		      <div class="my-container flex-desktop flex-middle">
		        <div class="widthHalf-desktop relative position-right-desktop50">
		          <figure class="relative map-img" >
		            <div class="absolute" style={{top:116+"px;", left:66+"px;"}}>
		              <div class=" pulsating-circle" ></div>
		            </div>

		            <div class="absolute" style={{top:104+"px;", right:66+"px;"}}>
		              <div class="pulsating-circle-delay2" ></div>
		            </div>

		            <div class="absolute" style={{top:77+"px;", left:260+"px;"}}>
		              <div class="pulsating-circle-delay4" ></div>
		            </div>
		            

		            <img src="./world-connection-pattern.png" class="width100" />
		          </figure>
		        </div>


		        <div class="widthHalf-desktop padding10 ">
		        	<div class=" relative position-left-desktop80">

		        			<div class="block-section relative ">
					        	<h2 class="color-black font2em text-uppercase">Obtén acceso a la economía global.</h2>
					        </div>
				          <div class="padding5"></div>

				          <div class="relative margin-bottom20">
				            <p><span class="font1-5em">Bitcoin creará una nueva élite económica en los años venideros. La pandemia del COVID-19 ha revelado los serios problemas del sistema financiero actual, así como los beneficios de Bitcoin sobre él.</span></p>
				          </div>

				          <div class="relative">
				            <p class="margin-bottom10 flex flex-middle">
				              <span class="margin-right10 ion-android-checkmark-circle color-green font2em"></span>
				              <span class="font1-5em">Bitcoin es el oro digital.</span>
				            </p>

				            <p class="margin-bottom10 flex flex-middle">
				              <span class="margin-right10 ion-android-checkmark-circle color-green font2em"></span>
				              <span class="font1-5em">Miles de empresas en el mundo aceptan Bitcoin.</span>
				            </p>

				            <p class="flex flex-middle">
				              <span class="margin-right10 ion-android-checkmark-circle color-green font2em"></span>
				              <span class="font1-5em">Bitcoin es la red más fuerte de la historia que funciona 24/7.</span>
				            </p>
				          </div>
		        		
		        	</div>
		          
		        </div>
		        
		      </div>
		      <br />
		      <br />
		      <br />
		    </section>

		    <section class="padding10" style={{background:"#F3F8FB;"}}>
		      <span class="relative" style={{top:-55+"px;"}} id="scrolledPlans" ></span>
		      <br />

		      <div class="my-container" >
		        
		        <div class=" flex flex-center">
		          <h2 class="color-black font2em text-uppercase margin-bottom10">Planes</h2>
		        </div>
		        <div class="flex flex-middle flex-center">
		          <div class="back-green" style={{width:40+"px;", height:5+"px;"}}></div>
		        </div>



		        <div class="margin10">
		        	<h3 class="font2em color-darkblue text-center">"Atrevete a descubrir el potencial de Bitcoin"</h3>
		        </div>


		        <div class="margin-bottom20 flex flex-center">
		          <p class="text-center color-darkblue" style={{maxWidth:690+"px;"}}><span class="font1-5em text-center">Accede a los <span class="font-bold" style={{fontSize: 1.02+"em;"}}>servicios y educación</span> para usarlo de forma <span class="font-bold" style={{fontSize: 1.02+"em;"}}>fácil y segura.</span></span> <br />

		          	<span class="font1-5em text-center">Tú decides, ser víctima o entrar a esta nueva revolución tecnológica.</span> 
		          </p>

		          
		        </div>

		        <div class="margin-bottom20">
		        	<h3 class="color-green font1-7em text-center">Adquiere tu plan por sólo:</h3>
		        </div>

		        <div class=" flex-desktop flex-center box-plan">
		          <div class="box-plan-item">
		            <p class="font1-3em color-green">Básico</p>

		            <div class="margin20-0">
		              <p class="font2-8em font-bold color-darkblue">$21.00</p>
		              <p class="font20 color-darkblue">/ 3 meses</p>
		            </div>
		            

		            <div class="margin-bottom10">
		            	<ul class="text-center color-darkblue" style={{listStyle:"none;"}}>
		            		<li class="text-center"><span class="color-green">•</span> Cursos Bitcoin</li>
		            		<li class="text-center"><span class="color-green">•</span> Asesoría mensual (30 min.)</li>
		            		<li class="text-center"><span class="color-green">•</span> Pagos en Bitcoin</li>
		            	</ul>
		            	<p class="color-green margin-top10">y más ...</p>
		            </div>

		            <button class="my-btn back-white color-green contactanos">
		              <span class="font1-3em color-green">Empezar ahora</span>
		            </button>
		          </div>

		          <div class="box-plan-item">
		            <p class="font1-3em color-green">Experto</p>

		            <div class="margin20-0">
		              <p class="font2-8em font-bold color-darkblue">$59.00</p>
		              <p class="font20 color-darkblue">/mes</p>
		            </div>
		            

		            <div class="margin-bottom10">
		            	<ul class="text-center color-darkblue" style={{listStyle:"none;"}}>
		            		<li class="text-center"><span class="color-green">•</span> Escuela Bitcoin Basic</li>
		            		<li class="text-center"><span class="color-green">•</span> Asesoría mensual (1 hrs.)</li>
		            		<li class="text-center"><span class="color-green">•</span> Pagos en Bitcoin</li>
		            		<li class="text-center"><span class="color-green">•</span> Accesso a pool de productos</li>
		            	</ul>
		            	<p class="color-green margin-top10">y más ...</p>
		            </div>

		            <button class="my-btn back-darkblue-gradient color-green">
		              <span class="font1-3em color-white">Empezar ahora</span>
		            </button>
		          </div>


		          <div class="box-plan-item">
		            <p class="font1-3em color-green">Corporativo</p>

		            <div class="margin20-0">
		              <p class="font2-8em font-bold color-darkblue">$357.00</p>
		              <p class="font20 color-darkblue">/mes</p>
		            </div>
		            

		            <div class="margin-bottom10">
		            	<ul class="text-center color-darkblue" style={{listStyle: "none;"}}>
		            		<li class="text-center"><span class="color-green">•</span> Asesorīa empresarial especializada</li>

		            		<li class="text-center"><span class="color-green">•</span> Escuela Bitcoin Full</li>
		            		<li class="text-center"><span class="color-green">•</span> Asesoría mensual (3 hrs.)</li>
		            		<li class="text-center"><span class="color-green">•</span> Pagos en Bitcoin</li>
		            		<li class="text-center"><span class="color-green">•</span> Accesso a pool de productos</li>
		            	</ul>
		            	<p class="color-green margin-top10">y más ...</p>
		            </div>

		            <button class="my-btn back-white color-green">
		              <span class="font1-3em color-green">Empezar ahora</span>
		            </button>
		          </div>
		        </div>

		        <br />
		        <br />
		      </div>
		    </section>

		    <section class="back-white padding10">
		      

		      <div class="my-container">

		        <article class="padding20-0 margin-top20">
		          <div>
		            <h3 class="color-gray font1-5em">Beneficios de Bitcoin</h3>
		          </div>
		          <div class="block-section">
		            <h2 class="color-black font1-5em text-uppercase">Únete a la evolución y acepta Bitcoin en tu negocio.</h2>
		          </div>
		        </article>
		        <article class="section-benefits flex-desktop">
		          <div class="section-benefits-item">
		            <div class="flex flex-center">
		              <figure class="section-benefits-item-img">
		                <img src="./accept-worldwide.svg" class="width100" />
		              </figure>
		            </div>
		            
		            <h3 class="section-benefits-item-title">Aceptado Mundialmente</h3>
		            <p class="section-benefits-item-text">Los Bitcoins obtenidos como medio de pago los puedes utilizar en cualquer parte del mundo.</p>
		          </div>

		          <div class="section-benefits-item">
		            <div class="flex flex-center">
		              <figure class="section-benefits-item-img">
		                <img src="./decentralized-currency.svg" class="width100" />
		              </figure>
		            </div>
		            
		           
		            <h3 class="section-benefits-item-title">Fácil Instalación</h3>

		            <p class="section-benefits-item-text">El levantamiento de cuenta toma sólo 7 minutos. Además el proceso es muy simple.</p>
		          </div>


		          <div class="section-benefits-item">
		            <div class="flex flex-center">
		              
		              <figure class="section-benefits-item-img">
		                <img src="./safe-and-secure-bitcoin.svg" class="width100" />
		              </figure>
		            </div>
		            
		            <h3 class="section-benefits-item-title">Seguro y Rápido</h3>
		            <p class="section-benefits-item-text">Los pagos solo tardan unos segundos en verse reflejados. Nunca tendras que esperar demasiado como lo haces con tarjetas de crédito/debito.</p>
		          </div>

		        </article>


		        <article class="section-benefits flex-desktop">

		          <div class="section-benefits-item">
		            <div class="flex flex-center">
		              <figure class="section-benefits-item-img">
		                <img src="./low-risk.svg" class="width100" />
		              </figure>
		            </div>
		            
		            <h3 class="section-benefits-item-title">Pagos Fáciles</h3>
		            <p class="section-benefits-item-text">El usuario solo escanea el código con su celular y confirma transacción.</p>
		          </div>

		          <div class="section-benefits-item">
		            <div class="flex flex-center">
		              <figure class="section-benefits-item-img">
		                <img src="./digital-cash-payment.svg" class="width100" />
		              </figure>
		            </div>
		            
		            <h3 class="section-benefits-item-title">Núlo Riesgo de Inflación</h3>
		            <p class="section-benefits-item-text">En el mundo solo puede haber 21 millones de Bitcoins. Nó más. Lo que fomenta es un sistema económico DEFLACIONARIO.</p>
		          </div>
		        </article>
		      </div>

		      
		    </section>

        <section class="contact back-white" >
		        {/* <!-- <div class="contact-circle hide flex-desktop"></div> --> */}

		        <article class="flex my-container width100">
		          <div class=" contact-form width100">

		            <figure class="contact-form-img" >
		              <img src="./contact-footer.svg"  alt="comprar bitcoin" class="width100" />
		            </figure>
		            <form class="contact-form-item" id="contact-form">
		            	<span id="scrolledContactanos" class="relative" style={{top:-50+"px;"}}></span>
		                <div class="padding-top20">
		                  <p class="color-white font2em text-center">Contáctanos:</p>
		                </div>
		                <div class="padding-top10 margin-bottom30">
		                  <p class="color-white font1-3em text-center" >Escríbenos, Estamos seguros de resolver tus dudas.</p>
		                </div>

		                <div class="contact-form-item-row">
		                  <div class="width100 flex contact-form-item-row-left">
		                  	
		                    <input type="text" name="user_name" placeholder="Nombre completo" class="my-input" required minlength="3" />
		                  </div>

		                  <div class="width100 flex ">
		                    <input type="text" name="user_email" placeholder="Email" class="my-input" required minlength="8" />
		                  </div>
		                </div>


		                <div class="contact-form-item-row">
		                  <div class="width100 flex contact-form-item-row-left">
		                    <input type="text" name="contact_number" placeholder="Teléfono" class="my-input" required minlength="8" />
		                  </div>

		                  <div class="width100 flex">
		                    <div class="my-select width100 color-darkblue back-white flex flex-middle" style={{color:"white !important;"}}>
		                        <select  class="color-darkblue " style={{paddingRight:34+"px;", height:100+"%;"}} required>
		                          <option class=""> <span>¿Qué Necesitas?</span></option>

		                          <option value="" class="color-gray">Quiero recibir Bitcoin</option>
		                          <option value="" class="color-gray">Educación</option>
		                          <option value="" class="color-gray">Cards</option>

		                        </select>
		                        <div class="my-select-icon color-black back-white flex flex-middle">
		                          <span class="ion-arrow-down-b color-darkblue"></span>
		                        </div>
		                    </div>
		                  </div>
		                </div>

		                <div class=" contact-form-item-row">
		                  <div class="width100 flex">
		                    <input type="text" name="message" placeholder="Cuéntanos a detalle qué" class="my-input" required minlength="10" />
		                  </div>
		                </div>


		                <div class="flex flex-right contact-form-item-btn">
		                  <button type="submit" class="my-btn back-green color-green"><span class="color-white">ENVIAR</span></button>
		                </div>

		                <div class="padding10"></div>
		            </form>

		            <div class="contact-form-data">
		              <h3 class="text-center color-darkblue font2em margin-bottom20 ">Llámanos: (33) 1342-49-40</h3>

		              <p class="font1-5em text-center">Mar Mediterráneo #1255 Col. Country Club <br/>
		                  Guadalajara, Jalisco, Mexico. <br />
		                  bitpayermx@gmail.com</p>
		            </div>
		          </div>
		        </article>
		    </section>
        </main>

        <Footer />
      </div>
    </div>
  )
}
