import Head from 'next/head'
import Link from 'next/link'

import Header from '../components/Header.jsx'
import Content from '../components/Content.jsx'


import Image from 'next/image'

export default function Home() {
  return (
    <div id="app-container">
      <div>
        <Head>
          <title>Bitpayer - Bitcoin hecho fácil.</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
          <link href="https://fonts.googleapis.com/css?family=Poppins|Lakki+Reddy|Rancho&display=swap" rel="stylesheet" />
         
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        </Head>

        <main>
          <h1 className="color-green">Bitpayer Loaded</h1>
        </main>

        <footer class="footer"></footer>
      </div>
    </div>
  )
}
