import React from 'react';
import Head from 'next/head'
import Header from '../../components/Header.jsx'
import Footer from '../../components/Footer.jsx'


const Education = () => {
    return (
        <div>
            <div>
                <Head>
                <title>Bitpayer - educacion.</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" type="text/css" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Sarabun:ital,wght@0,200;0,300;0,400;0,600;0,800;1,300;1,400;1,600;1,800&family=Vollkorn&display=swap" rel="stylesheet" />
                </Head>

                <Header />

                <main>
                    <section class="position-top-section border-top-3-blue">
                        <div>
                            <section class="back-darkblue-gradient width100 padding10">

                                <article class="my-container">

                                    <div class="flex flex-middle flex-between">
                                        <div class="widthHalf-desktop">
                                            <h2 class="font2-5em color-white margin-bottom20">Bitpayer <span class="color-green">Educación en Bitcoin</span> te llevará al siguiente nivel.</h2>

                                            <p class="font1-5em color-white margin-bottom20">		Desarrolla tus habilidades o las de tu equipo empresarial para estar a la vanguardia del cambio económico/tecnológico mundial.</p>

                                            <div>
                                                <button class="my-btn back-green color-green call-wrap-actions-button">
                                                    <span class="font1em color-white">Agendar ahora</span>
                                                </button>

                                                <p class="color-yellow anchor font20">¿Cómo funciona?</p>
                                            </div>
                                            
                                        </div>

                                        <div class="widthHalf-desktop relative flex flex-right">
                                            <figure class="relative" style={{width:420+"px;", bottom:-60+"px;", right:30+"px;"}}>
                                                <img src="./estudio.png" class="width100" />
                                            </figure>
                                        </div>
                                    </div>

                                    
                                </article>

                                
                            </section>

                            
                            <div class="padding20"></div>
                            <div class="padding20"></div>
                            

                            <section class="padding20">
                                <article class="courses flex padding0-20">
                                    <div class="courses-item relative" >
                                        <span class="absolute badge-educate-item-price padding5">
                                            <span class="font15 font-bold color-white">Proximamente!</span>
                                        </span>
                                        <figure class="width100" class="courses-item-img" >
                                            <img src="./wallets-course.png" class="width100" />
                                        </figure>

                                        <div class="padding10-20" style={{paddingBottom: 0}}>
                                            <h3 class="font20 text-center">Elección de wallets para criptomonedas.</h3>
                                        </div>
                                        <div class="padding10">
                                            <p class="font17 text-center">Guardar de forma segura tu Bitcoin es unos de los pasos que pueden resultarte más engorrosos. En este curso hemos hecho el trabajo duro por ti y te enseñamos cómo hacerlo de forma segura y rápida.</p>
                                        </div>

                                        <div class="padding10" style={{position: 'static;'}}>
                                        <button class="my-btn back-darkblue-gradient block color-green" style={{width: 100+"%"}}>
                                            <span class="font1-3em color-white">Comenzar Curso</span>
                                        </button>
                                        </div>
                                    </div>


                                    <div class="courses-item relative" >
                                        <span class="absolute badge-educate-item-price padding5">
                                            <span class="font15 font-bold color-white">Gratis!</span>
                                        </span>
                                        <figure class="width100" class="courses-item-img">
                                            <img src="./bitcoin-course.png" class="width100" />
                                        </figure>

                                        <div class="padding10-20" style={{paddingBottom: 0}}>
                                            <h3 class="font20 text-center">Introduccion a Bitcoin y Blockchain.</h3>
                                        </div>
                                        <div class="padding10">
                                            <p class="font17 text-center">En este curso, el profesor te guiará a través de lo que es Bitcoin, te explicará cómo obtener y usar bitcoin, cómo se deriva el precio de bitcoin, la línea de tiempo de la transacción y mucho más.</p>
                                        </div>

                                        <div class="padding10" style={{position: 'static'}}>
                                        <button class="my-btn back-darkblue-gradient block color-green" style={{width: 100+"%;"}}>
                                            <span class="font1-3em color-white">Comenzar Curso</span>
                                        </button>
                                        </div>
                                    </div>

                                    <div class="courses-item relative" >
                                        <span class="absolute badge-educate-item-price padding5">
                                            <span class="font15 font-bold color-white">Proximamente!</span>
                                        </span>
                                        <figure class="width100" class="courses-item-img" >
                                            <img src="./multisig-course.png" class="width100" />
                                        </figure>

                                        <div class="padding10-20" style={{paddingBottom: 0}}>
                                            <h3 class="font20 text-center">Creación y manejo de carteras multi-firma.</h3>
                                        </div>
                                        <div class="padding10">
                                            <p class="font17 text-center">La mayor fortaleza de Bitcoin también es una debilidad. Una frase, o 32 bytes de secreto, puede proteger y mover miles de millones de dólares. Con multi-firma, el riesgo se minimiza bastante.</p>
                                        </div>

                                        <div class="padding10" style={{position: 'static'}}>
                                        <button class="my-btn back-darkblue-gradient block color-green" style={{width: 100+"%;"}}>
                                            <span class="font1-3em color-white">Comenzar Curso</span>
                                        </button>
                                        </div>
                                    </div>
                                </article>
                            </section>
                            
                            <div class="padding20"></div>
                            <div class="padding20"></div>
                            <div class="padding20"></div>
                            <div class="padding20"></div>
                            <div class="padding20"></div>
                        </div>


                    </section>
                    
                </main>

                <Footer/>
            </div>
        </div>
    );
}

export default Education;
